server:
  port: 8081
  error:
    whitelabel:
      enable: true
zuul:
  routes:
    users:
      path: /exceptiontest/**
      url: http://192.168.0.156:8083
      stripPrefix: false
ribbon:
  eureka:
    enabled: false